name: GameBladePlugin
author: 'storm345'
main: org.stormdev.gbplugin.plugin.core.GameBlade
version: 1.0
softdepend: [uCars, uPlanes, uCarsTrade]

commands:
    mod:
        description: Mod command
        aliases: [admin]
        permission: gameblade.admin
        permission-message: Unknown command. Type \"/help\" for help.
        usage: /<command>
        default: op
    broadcast:
        description: Broadcast a message
        aliases: [bc]
        permission: gameblade.admin
        permission-message: Unknown command. Type \"/help\" for help.
        usage: /<command> <Message>
        default: op