name: GameBladePlugin
author: 'storm345'
main: org.stormdev.gbplugin.plugin.core.GameBlade
version: 1.0
softdepend: [uCars, uPlanes, uCarsTrade]

commands:
    mod:
        description: Mod command
        aliases: [admin]
        permission: gameblade.admin
        usage: /<command>
        default: op