name: GameBladePlugin
author: 'storm345'
main: org.stormdev.gbplugin.plugin.core.GameBlade
version: 1.0
softdepend: [uCars, uPlanes, uCarsTrade, ServerManager, MarioKart]

commands:
    mod:
        description: Mod command
        aliases: [admin]
        permission: gameblade.admin
        permission-message: Unknown command. Type \"/help\" for help.
        usage: /<command>
        default: op
    broadcast:
        description: Broadcast a message
        aliases: [bc]
        permission: gameblade.admin
        permission-message: Unknown command. Type \"/help\" for help.
        usage: /<command> <Message>
        default: op
    servers:
        description: Join a server
        aliases: [changeserver]
        usage: /<command>
        default: true
    mytokens:
        description: View how many tokens you have
        usage: /<command>
    givetokens:
        description: Give tokens to player
        usage: /<command> <Player> <Tokens>
        permission: mta.admin.tokens
        permission-message: You don't have the permission <permission> needed to award tokens!
        default: op
    mystars:
        description: View how many stars you have
        usage: /<command>
    givestars:
        description: Give stars to a player
        usage: /<command> <Player> <Tokens>
        permission: mta.admin.stars
        permission-message: You don't have the permission <permission> needed to award tokens!
        default: op