name: GameBladePlugin
author: 'storm345'
main: org.stormdev.gbplugin.plugin.core.GameBlade
version: 1.0
softdepend: [uCars, uPlanes, uCarsTrade, ServerManager, MarioKart]

commands:
    mod:
        description: Mod command
        aliases: [admin]
        permission: gameblade.admin
        permission-message: Unknown command. Type "/help" for help.
        usage: /<command>
        default: op
    ban:
        description: Ban command
        aliases: [tempban, punish]
        permission: gameblade.admin
        permission-message: Unknown command. Type "/help" for help.
        usage: /<command>
        default: op
    kick:
        description: Kick command
        aliases: [arsekick]
        permission: gameblade.admin
        permission-message: Unknown command. Type "/help" for help.
        usage: /<command>
        default: op
    warn:
        description: Kick command
        aliases: [nag]
        permission: gameblade.admin
        permission-message: Unknown command. Type "/help" for help.
        usage: /<command>
        default: op
    pardon:
        description: Unban command
        aliases: [unban]
        permission: gameblade.admin
        permission-message: Unknown command. Type "/help" for help.
        usage: /<command> <Name>
        default: op
    broadcast:
        description: Broadcast a message
        aliases: [bc]
        permission: gameblade.admin
        permission-message: Unknown command. Type "/help" for help.
        usage: /<command> <Message>
        default: op
    servers:
        description: Join a server
        aliases: [changeserver]
        usage: /<command>
        default: true
    mytokens:
        description: View how many tokens you have
        usage: /<command>
    createmenuvillager:
        description: Create a menu villager
        aliases: [cmv]
        usage: /<command> <Name>
        permission: gameblade.admin
        permission-message: You don't have the permission <permission> needed to award tokens!
        default: op
    givetokens:
        description: Give tokens to player
        usage: /<command> <Player> <Tokens>
        permission: gameblade.admin
        permission-message: You don't have the permission <permission> needed to award tokens!
        default: op
    mystars:
        description: View how many stars you have
        usage: /<command>
    starshop:
        description: Access the star shop
        usage: /<command>
    hat:
        description: Wear hats you own
        usage: /<command>
    givestars:
        description: Give stars to a player
        usage: /<command> <Player> <Tokens>
        permission: gameblade.admin
        permission-message: You don't have the permission <permission> needed to award tokens!
        default: op